ARG TARGETARCH=amd64

### Base builder image for native builds architecture
FROM golang:1.17-alpine AS builder-native-base
ENV CGO_ENABLED=1 GOOS=linux
RUN apk add --no-cache \
    libpcap-dev \
    g++ \
    curl \
    build-base \
    binutils-gold \
    bash \
    clang \
    llvm \
    libbpf-dev \
    linux-headers
COPY ./install-capstone.sh .
RUN ./install-capstone.sh


### Intermediate builder image for x86-64 to x86-64 native builds
FROM builder-native-base AS builder-from-amd64-to-amd64
ENV GOARCH=amd64
ENV BPF_TARGET=amd64 BPF_CFLAGS="-O2 -g -D__TARGET_ARCH_x86"


### Intermediate builder image for AArch64 to AArch64 native builds
FROM builder-native-base AS builder-from-arm64v8-to-arm64v8
ENV GOARCH=arm64
ENV BPF_TARGET=arm64 BPF_CFLAGS="-O2 -g -D__TARGET_ARCH_arm64"


### Final builder image where the build happens
# Possible build strategies:
# TARGETARCH=amd64
# TARGETARCH=arm64v8
ARG TARGETARCH=amd64
FROM builder-from-${TARGETARCH}-to-${TARGETARCH} AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

WORKDIR /app/tracer
RUN rm *_bpfel_*
RUN GOARCH=${TARGETARCH} go generate tracer.go

WORKDIR /app

RUN go build -ldflags="-extldflags=-static -s -w" -o worker .

### The shipped image
ARG TARGETARCH=amd64
FROM ${TARGETARCH}/alpine:latest

ENV GIN_MODE=release

WORKDIR /app/import/
WORKDIR /app/data/
WORKDIR /app

RUN apk add --no-cache ca-certificates && update-ca-certificates

COPY --from=builder ["/app/worker", "."]

ENTRYPOINT ["/app/worker"]
